# Site
repository: shellcodesniper/shellcodesniper.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: KIM DOGYUN
title: R&D Dev Team Lead
email: root@ql.gl
email_title: MAIL_HERE
phone: +82-10-8222-1920
phone_title: M-PHONE
website: https://ql.gl
website_title: WEB!

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  shellcodesniper
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: kuuwange
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-EC051SJ5MV"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile_image.png
about_content: | # this will include new lines to allow paragraphs
  `í˜¸ê¸°ì‹¬ Qurious, ë°ê³  LMAO, ë„ˆë“œí•˜ì§€ë§Œ GEEK, ì‚¶ì„ ì¦ê¸°ëŠ” LIFE` ì €ë¥¼ ì„¤ëª…í•  ìˆ˜ ìˆëŠ” ë‹¨ì–´ì…ë‹ˆë‹¤.<br/>
  Linux Kernel / Low Level / System ë™ì‘ êµ¬ì¡° ë“± ë„ˆë“œ í•˜ê³  ì§„ì…í•˜ê¸° ì–´ë µì§€ë§Œ, ê·¸ ì†ì˜ ê¹Šì€ ë™ì‘ì›ë¦¬ì— ëŒ€í•œ ê¹Šì€ ê´€ì‹¬ê³¼ ì• ì •<br/>
  Open-Source & Closed-Source ë‘ê°€ì§€ì˜ ì¡°í™”ë¡œ ë¹ ë¥´ì§€ë§Œ ì•ˆì •ì ì´ê³  ì•ˆì •ì ì´ì§€ë§Œ ìƒì‚°ì ì¸, ëª¨ìˆœì ì¸ ìƒí™©ì„ í•´ê²°í•´ë‚´ëŠ”<br/>
  ì„ê¸°ì‘ë³€, ë¬´ê±°ìš´ ìƒí™©ì—ì„œ ë”ìš± ë¹›ì„ ë°œí•˜ëŠ” ë¦¬ë“œ `ì¡ë¶€` ì…ë‹ˆë‹¤.<br/>

ignore_this: |
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>
    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        border: weak # Value of `weak` will display a weak border below this item. # Any 
        title: [Open-Source] Nvim-Tree
        link: https://github.com/nvim-tree/nvim-tree.lua/pull/1566
        link_text: PR_LINK
        additional_links:
          - title:  github
            icon: fab fa-github
            url: https://github.com/shellcodesniper/nvim-tree.lua
        quote: >
          Nvim Tree Mix-in Sorter for File&Folder Ordering View
        description: | # this will include new lines to allow paragraphs
          Open-Source Contributing
      - layout: right
        border: weak # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: [Open-Source] SimpleDeployer
        link: https://github.com/shellcodesniper/SimpleDeployer
        link_text: PROJECT_LINK
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/shellcodesniper/SimpleDeployer
        quote: >
          Rust / Docker API / NginX
        description: | # this will include new lines to allow paragraphs
          Built-in Support Nginx + Cloudflare + .env
          Red - Green Simple Deployer for Reverse-Proxy NginX

      - layout: right
        border: weak # Value of `weak` will display a weak border below this item. # Any 
        title: BLUEPRINT
        link: https://github.com/shellcodesniper/RUST_BP
        link_text: PROJECT_LINK
        additional_links:
          - title:  Link to Project
            icon: fab fa-github
            url: https://github.com/shellcodesniper/RUST_BP
        quote: >
          Boilerprint of RUST
        description: | # this will include new lines to allow paragraphs
          Boilerprint of RUST

      - layout: right
        border: weak # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: HOW_TO_SERIES
        link: https://bdev.io
        link_text: WIKI_LINK
        additional_links:
          - title:  github_link
            icon: fab fa-github
            url: https://github.com/shellcodesniper/how_to_series
        quote: >
          WIKI FOR BECOME DEVELOPER
        description: | # this will include new lines to allow paragraphs
          SHORT DAILY WIKI

      # - layout: right
      #   border: weak # Value of `weak` will display a weak border below this item. # Any 
      #   title: Project name
      #   link: link url
      #   link_text: PROJECT_LINK
      #   additional_links:
      #     - title:  Link to Project
      #       icon: fab fa-github
      #       url: Link to Project
      #   quote: >
      #     Short overview of the project (optional)
      #   description: | # this will include new lines to allow paragraphs
      #     Description about the work on/with the project
      # - layout: right
      #   border: weak # Value of `weak` will display a weak border below this item. # Any 
      #                 # other value (or no value) means no border will be displayed
      #   title: Project name
      #   link: link url
      #   link_text: PROJECT_LINK
      #   additional_links:
      #     - title:  Link to Project
      #       icon: fab fa-github
      #       url: Link to Project
      #   quote: >
      #     Short overview of the project (optional)
      #   description: | # this will include new lines to allow paragraphs
      #     Description about the work on/with the project





  - title: Experience
    layout: list
    content:
      - layout: right
        border: weak
        title: ì—ì´ë¼ì´ë¸Œ
        sub_title: ì±…ì„
        caption: 2015.12-2016.10
        #link: 
        quote: >
          Web Publishing
        description: | # this will include new lines to allow paragraphs
          Web Publishing & Backend
      - layout: right 
        border: weak
        title: Caramella
        sub_title: R&D ê°œë°œíŒ€ íŒ€ì¥
        caption: 2016.11 ~ Present
        link: https://caramella.kr
        quote: >
          Tech Support / System Level Tech Develop / Backend Develop
        # description: | # this will include new lines to allow paragraphs
        #   ê¸°ìˆ  ì§€ì› / ì‹œìŠ¤í…œ ì• í”Œë¦¬ì¼€ì´ì…˜ ê°œë°œ / ë”¥ëŸ¬ë‹ í”„ë¡œê·¸ë¨ ê°œë°œ ì§€ì› / API ì„œë²„ ê°œë°œ
      - layout: right
        border: weak
        title: YoungNYoung
        sub_title: í”„ë¦¬ëœì„œ
        caption: 2017.5 ~ 2017.11
        #link: 
        quote: >
          ì²­ë…„ì°½ì—…ë‹¨ í™ˆí˜ì´ì§€ ê°œë°œ
        # description: | # this will include new lines to allow paragraphs
        #   í’€ìŠ¤íƒ ê°œë°œ ìœ ì§€ë³´ìˆ˜
      - layout: right 
        border: weak
        title: Je-Clean
        sub_title: í”„ë¦¬ëœì„œ
        caption: 2017.5 ~ 2017.11
        link: https://jeclean.com
        quote: >
          ì›¹ ì• í”Œë¦¬ì¼€ì´ì…˜ ê°œë°œ
        # description: | # this will include new lines to allow paragraphs
        #   í’€ìŠ¤íƒ ê°œë°œ ìœ ì§€ë³´ìˆ˜
      - layout: right
        border: weak
        title: MintToy
        sub_title: í”„ë¦¬ëœì„œ
        caption: 2018.10 ~ 2019.04
        link: https://selfietoy.net
        quote: >
          AI ì–¼êµ´ì¸ì‹ íŒŒíŠ¸
        # description: | # this will include new lines to allow paragraphs
        #   ì–¼êµ´ì¸ì‹ ëª¨ë“ˆ ì œê³µ
      - layout: right 
        border: weak
        title: ì œì£¼ëŒ€í•™êµ
        sub_title: í•™ì‚¬ ì—°êµ¬ì›
        caption: 2018.10-2019.12
        link: http://multimediacorpus.com
        quote: >
          í•™ìŠµë³´ì¡°ë„êµ¬
        # description: | # this will include new lines to allow paragraphs
        #   ì¼ë³¸ ì–´í•™ í•™ìŠµ ë³´ì¡° ì‚¬ì´íŠ¸ ê°œë°œ
      - layout: right
        border: weak
        title: 13hz
        sub_title: #
        caption: 2020.03 - 2021.05
        link: https://d-ocean.kr
        quote: >
          ì„¤ê³„ / ë°±ì—”ë“œ
        # description: | # this will include new lines to allow paragraphs
        #   ë°ì´í„°ë² ì´ìŠ¤ ì„¤ê³„ ë° ë°±ì—”ë“œ
      - layout: right 
        border: weak
        title: andS
        sub_title: ë©˜í† 
        caption: 2020.5 - 2020.10
        #link: 
        quote: >
          voice over ip ê¸°ìˆ ì„ ì´ìš©í•œ ì•ˆë“œë¡œì´ë“œ ê¸°ë°˜ í†µì‹  ì•± ë©˜í† ë§
        # description: | # this will include new lines to allow paragraphs
        #   ì•±ìŠ¤í† ì–´ ì¶œì‹œê¹Œì§€
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Bachelor ( Expected graduation date 2023. 02 )
        sub_title: BA Computer Engineering
        caption: 2016 - 2023
        quote: >
          Jeju National University (2016 - 2023<Expected graduation date 2023. 02)
        description: | # this will include new lines to allow paragraphs
          Expected graduation date 2023.02
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      <div> 
        <div align="right" style="display: flex;">
          <span dir="auto">
            <a href="https://hits.seeyoufarm.com" rel="nofollow"><img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2Fshellcodesniper%2F&count_bg=%2379C83D&title_bg=%23555555&icon=hashnode.svg&icon_color=%23E7E7E7&title=HIT%21&edge_flat=true" style="max-width: 100%;"></a>
          </span>
        </div>
        <div align="left" style="display: flex;">
          <b>Hi there ğŸ‘‹ || ì•ˆë…•í•˜ì„¸ìš”! ğŸ‘‹</b>
        </div> 
      </div>
      <br />

      <!-- íŠ¸ë¡œí”¼! -->
      <div align="center">
        <img align="middle" src="https://github-profile-trophy.vercel.app/?username=shellcodesniper&theme=chalk&rank=SECRET,SSS,SS,S,AAA,AA,A,B&margin-w=15&margin-h=15&column=5" />
      </div>
      <br />

      <!-- ë‚˜ì¤‘ì— ì¶”ê°€í• ê²ƒ : https://www.hackerrank.com/ -->

      <!-- ì—°ë½ì²˜ -->
      <div align="center">
        <b>CONTACT</b>:&nbsp;&nbsp;
        <a href="mailto:admin@bdev.io">
          <img align="center" src="https://img.shields.io/badge/MAIL-D14836?style=for-the-badge&logo=gmail&logoColor=white">
        </a>&nbsp;&nbsp;
        <b>HOMEPAGE</b>:&nbsp;&nbsp;
        <a href="https://ql.gl/">
          <img align="center" src="https://img.shields.io/badge/QL.GL-0A0A0A?style=for-the-badge&logo=devdotto&logoColor=white">
        </a>&nbsp;&nbsp;
        <b>INSTAGRAM</b>:&nbsp;&nbsp;
          <a href="https://www.instagram.com/kuuwange" rel="nofollow">
            <img align="center" src="https://img.shields.io/badge/INSTA-E4405F?style=for-the-badge&logo=instagram&logoColor=white">
          </a>&nbsp;&nbsp;
        <b>LINKEDIN</b>:&nbsp;&nbsp;
          <a href="https://www.linkedin.com/in/kuuwange" rel="nofollow">
            <img align="center" src="https://img.shields.io/badge/LINKED-0077B5?style=for-the-badge&logo=linkedin&logoColor=white">
          </a>&nbsp;&nbsp;
      </div>
      <br />

      <!-- ê¸°ìˆ  -->

      ### I Love This
      ![MacOS](https://img.shields.io/badge/macOS-black?&style=for-the-badge&logo=macOS&logoColor=white)&nbsp;
      ![Rust](https://img.shields.io/badge/Rust-E57324?style=for-the-badge&logo=rust&logoColor=black)&nbsp;
      ![NodeVim](https://img.shields.io/badge/NeoVim-%2357A143.svg?&style=for-the-badge&logo=neovim&logoColor=white)&nbsp;
      ![GitHub Actions](https://img.shields.io/badge/github%20actions-%232671E5.svg?style=for-the-badge&logo=githubactions&logoColor=white)&nbsp;
      ![NestJS](https://img.shields.io/badge/nestjs-E0234E?style=for-the-badge&logo=nestjs&logoColor=white)&nbsp;
      ![GitHub](https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white)&nbsp;
      <br />
      ### EDITOR
      ![EditorConfig](https://img.shields.io/badge/Editor%20Config-E0EFEF?style=flat-square&logo=editorconfig&logoColor=000)&nbsp;
      ![.ENV](https://img.shields.io/badge/DOTENV-ECD53F?style=flat-squarege&logo=.env&logoColor=000)&nbsp;
      ![ESLint](https://img.shields.io/badge/ESLint-4B3263?style=flat-squarege&logo=eslint&logoColor=white)&nbsp;
      ### Frequently Use
      ![TypeScript](https://img.shields.io/badge/TypeScript-007ACC?style=flat-square&logo=typescript&logoColor=white)&nbsp;
      ![C](https://img.shields.io/badge/C-00599C?style=flat-square&logo=c&logoColor=white)&nbsp;
      ![Lua](https://img.shields.io/badge/Lua-2C2D72?style=flat-square&logo=lua&logoColor=white)&nbsp;
      ![Kafka](https://img.shields.io/badge/Apache_Kafka-231F20?style=flat-square&logo=apache-kafka&logoColor=white)&nbsp;
      ![TensorFlow](https://img.shields.io/badge/TensorFlow-FF6F00?style=flat-square&logo=TensorFlow&logoColor=white)&nbsp;
      ![Docker](https://img.shields.io/badge/Docker-2CA5E0?style=flat-square&logo=docker&logoColor=white)&nbsp;
      ![NginX](https://img.shields.io/badge/Nginx-009639?style=flat-square&logo=nginx&logoColor=white)&nbsp;
      ![Redis](https://img.shields.io/badge/redis-%23DD0031.svg?&style=flat-square&logo=redis&logoColor=white)&nbsp;
      ![Oracle](https://img.shields.io/badge/Oracle-F80000?style=flat-square&logo=Oracle&logoColor=white)&nbsp;
      ![Postgresql](https://img.shields.io/badge/PostgreSQL-316192?style=flat-square&logo=postgresql&logoColor=white)&nbsp;
      ![Cloudflare](https://img.shields.io/badge/Cloudflare-F38020?style=flat-square&logo=Cloudflare&logoColor=white)&nbsp;
      ![AWS](https://img.shields.io/badge/Amazon_AWS-FF9900?style=flat-square&logo=amazonaws&logoColor=white)&nbsp;
      ![Mac M](https://img.shields.io/badge/apple%20silicon-333333?style=flat-square&logo=apple&logoColor=white)&nbsp;
      ![Redhat](https://img.shields.io/badge/Red%20Hat-EE0000?style=flat-square&logo=redhat&logoColor=white)&nbsp;
      ![Yarn](https://img.shields.io/badge/yarn-%232C8EBB.svg?style=flat-square&logo=yarn&logoColor=white)&nbsp;
      ![Notion](https://img.shields.io/badge/Notion-%23000000.svg?style=flat-square&logo=notion&logoColor=white)&nbsp;
      ![Postman](https://img.shields.io/badge/Postman-FF6C37?style=flat-square&logo=postman&logoColor=white)&nbsp;
      ![Prometheus](https://img.shields.io/badge/Prometheus-E6522C?style=flat-square&logo=Prometheus&logoColor=white)&nbsp;
      ![Slack](https://img.shields.io/badge/Slack-4A154B?style=flat-square&logo=slack&logoColor=white)&nbsp;
      ![KakaoTalk](https://img.shields.io/badge/kakaotalk-ffcd00.svg?style=flat-square&logo=kakaotalk&logoColor=000000)&nbsp;
      ![Line](https://img.shields.io/badge/Line-00C300?style=flat-square&logo=line&logoColor=white)&nbsp;
      <br/>
      <!-- STATS -->
      <table width="100%">
        <tr>
          <th align="center">
            <img width="441" height="1">
            <p> 
              <small>
                Languages All Time
              </small>
            </p>
          </th>
          <th align="center">
            <img width="441" height="1">
              <p> 
              <small>
                Coding Activities (Since 2020)  
              </small>
            </p>
          </th>
        </tr>
        <tr>
          <td valign="top">
            <img src="https://wakatime.com/share/@KuuWangE/f6ea09a8-9b0c-41ba-b6a4-1fcf8798cc26.svg" width="100%">
          </td>
          <td valign="top">
            <img src="https://wakatime.com/share/@KuuWangE/468f48c1-1aa1-49ba-8f8b-dddf8feb3b3b.svg" width="100%">
          </td>
        </tr>
        <tr>
          <td colspan="2" style="width:100%">
            <div align="center">
              <img align="middle" width="100%" height="54" src="https://raw.githubusercontent.com/shellcodesniper/shellcodesniper/master/table_title.svg" />
            </div>
          </td>
        </tr>
        <tr>
          <td colspan="2" style="width:100%">
            <img src="https://wakatime.com/share/@KuuWangE/6e2a5d8e-578f-459e-bcc2-dee6662cc747.svg" width="100%">
          </td>
        </tr>
      </table>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
